#!/bin/bash
# Quick Start Guide for Production Membership ID System
# Run this checklist to get the system operational

echo "🚀 NUKAFS Membership ID System - Quick Start Guide"
echo "=================================================="
echo ""

# Step 1: Database Setup
echo "📝 Step 1: Database Schema"
echo "   1. Open Supabase Dashboard"
echo "   2. Go to SQL Editor"
echo "   3. Copy contents of: lib/supabase/schema-membership-updates.sql"
echo "   4. Paste into SQL Editor"
echo "   5. Execute"
echo "   ✓ Tables created: membership_identities, system_config"
echo ""
read -p "   Press Enter when done..."

# Step 2: Create Super Admin Account
echo ""
echo "👤 Step 2: Create Super Admin Account"
echo "   1. Use Supabase Auth dashboard or admin API"
echo "   2. Create user:"
echo "      Email: samuel540wisesamura@gmail.com"
echo "      Password: [temporary password]"
echo "      Role: super_admin (in metadata)"
echo "   3. Verify email exists in auth.users table"
echo ""
read -p "   Press Enter when done..."

# Step 3: Bootstrap Script
echo ""
echo "⚡ Step 3: Bootstrap Membership System"
echo "   1. Open terminal in project root"
echo "   2. Run: node scripts/bootstrap-membership-system.mjs"
echo ""
echo "   This will:"
echo "   ✓ Find Samuel Samura"
echo "   ✓ Assign NUKAFS-000001"
echo "   ✓ Generate verification token"
echo "   ✓ Create QR code"
echo "   ✓ Initialize counters"
echo ""
echo "   Example output:"
echo "   ✅ Bootstrap Complete!"
echo "   Super Admin: Samuel Samura"
echo "   Membership ID: NUKAFS-000001"
echo "   Verification Token: abc123..."
echo "   QR Code: https://registry.nukafs-sl.org/verify/abc123..."
echo ""
read -p "   Press Enter after running bootstrap..."

# Step 4: Profile Photo Upload
echo ""
echo "📸 Step 4: Upload Profile Photo"
echo "   1. Start dev server: pnpm dev"
echo "   2. Login as Samuel Samura"
echo "   3. Navigate to: /admin/profile-edit"
echo "   4. Click 'Upload Photo'"
echo "   5. Select provided profile image"
echo "   6. Click 'Save Changes'"
echo "   ✓ Photo uploaded and synced"
echo ""
read -p "   Press Enter when done..."

# Step 5: Test QR Code
echo ""
echo "🔍 Step 5: Test QR Code"
echo "   1. Generate QR code from verification URL:"
echo "      https://registry.nukafs-sl.org/verify/{token}"
echo "   2. Scan QR code with phone camera or scanner"
echo "   3. Should open verification page showing:"
echo "      ✓ Profile photo"
echo "      ✓ Name: Samuel Samura"
echo "      ✓ Membership ID: NUKAFS-000001"
echo "      ✓ Academic info"
echo "      ✓ Verified badge"
echo ""
read -p "   Press Enter when done..."

# Step 6: Test Next User
echo ""
echo "👥 Step 6: Test Next User Membership ID"
echo "   1. Register new student account"
echo "   2. Have Executive/Admin approve registration"
echo "   3. System should automatically allocate: NUKAFS-000002"
echo "   4. Verify in database or Digital ID Card"
echo "   5. Test QR code for second user"
echo ""
read -p "   Press Enter when done..."

# Step 7: Verify Database State
echo ""
echo "🗄️  Step 7: Verify Database State"
echo "   1. Check system_config table:"
echo "      student_membership_counter.next = 2 (after Samuel)"
echo "      stakeholder_membership_counter.next = 1"
echo ""
echo "   2. Check membership_identities table:"
echo "      - membership_id = 'NUKAFS-000001'"
echo "      - membership_type = 'student'"
echo "      - verification_token = '[64-char hex]'"
echo "      - qr_code_status = 'active'"
echo ""
echo "   3. Check audit_logs table:"
echo "      - action contains 'bootstrapped membership system'"
echo ""
read -p "   Press Enter when done..."

# Step 8: Production Deployment
echo ""
echo "🚀 Step 8: Production Deployment"
echo "   1. Update environment variables:"
echo "      - NEXT_PUBLIC_SUPABASE_URL"
echo "      - SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "   2. Run database migrations on production"
echo ""
echo "   3. Create Super Admin in production Supabase"
echo ""
echo "   4. Run bootstrap script on production"
echo ""
echo "   5. Upload profile photo in production"
echo ""
echo "   6. Test QR code in production"
echo ""
echo "   7. Monitor audit logs"
echo ""
read -p "   Press Enter when done..."

# Summary
echo ""
echo "✅ Setup Complete!"
echo ""
echo "Key Endpoints:"
echo "  POST   /api/membership-id              (allocate new ID)"
echo "  GET    /api/membership-id?action=...   (verify token)"
echo "  POST   /api/profile-photo-upload       (upload photo)"
echo "  GET    /api/member-details             (public info)"
echo "  PUT    /api/super-admin/profile        (edit profile)"
echo ""
echo "Key Files:"
echo "  lib/membership-id-system.ts            (ID generation)"
echo "  lib/supabase/storage-config.ts         (file storage)"
echo "  components/admin/super-admin-profile-editor.tsx  (UI)"
echo "  scripts/bootstrap-membership-system.mjs (setup)"
echo "  MEMBERSHIP_SYSTEM_GUIDE.md             (documentation)"
echo ""
echo "Testing Samuel Samura:"
echo "  Membership ID:     NUKAFS-000001"
echo "  Email:             samuel540wisesamura@gmail.com"
echo "  Phone:             +23279630777"
echo "  University:        Fourah Bay College"
echo "  Department:        Electrical and Electronics Engineering"
echo "  Level:             Year 4"
echo "  Skills:            Software Development"
echo ""
echo "Next User will receive:"
echo "  Membership ID:     NUKAFS-000002"
echo "  Type:              Sequential increment"
echo "  Sequence:          Automatic"
echo ""
echo "=================================================="
echo "System ready for production! 🎉"
